name: Test Package

on:
  push:
    paths:
      - "iso8583/**/*.py"
      - "tests/**/*.py"
  pull_request:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, pypy3]
    steps:
      - name: Clone Repository (Latest)
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref == ''

      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest

      - name: Test with pytest
        run: |
          python -m pytest --version
          python -m pytest

      - name: Test with mypy
        if: matrix.python-version != 'pypy3'
        run: |
          python -m pip install mypy
          python -m mypy --version
          python -m mypy

      - name: Test with flake8
        run: |
          python -m pip install flake8
          python -m flake8 --version
          python -m flake8
